"""Updated Users table

Revision ID: 03dd2daa43f3
Revises: 9382efb56520
Create Date: 2026-07-23 20:31:51.765089

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '03dd2daa43f3'
down_revision = '9382efb56520'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('quotation_requests')
    op.drop_table('projects')
    op.drop_table('quotation_items')
    op.drop_table('bills')
    op.alter_column('products', 'name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('products', 'price',
               existing_type=mysql.DECIMAL(precision=12, scale=2),
               type_=sa.Float(),
               nullable=False)
    op.drop_column('products', 'stock_quantity')
    op.drop_column('products', 'description')
    op.drop_column('products', 'category')
    op.add_column('quotations', sa.Column('product_id', sa.Integer(), nullable=False))
    op.add_column('quotations', sa.Column('quantity', sa.Integer(), nullable=False))
    op.add_column('quotations', sa.Column('total_price', sa.Float(), nullable=False))
    op.add_column('quotations', sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('quotations', sa.Column('price', sa.Float(), nullable=False))
    op.drop_constraint(op.f('fk_quotations_customer'), 'quotations', type_='foreignkey')
    op.drop_constraint(op.f('fk_quotations_creator'), 'quotations', type_='foreignkey')
    op.drop_column('quotations', 'created_at')
    op.drop_column('quotations', 'status')
    op.drop_column('quotations', 'created_by')
    op.drop_column('quotations', 'valid_until')
    op.drop_column('quotations', 'total_amount')
    op.drop_column('quotations', 'customer_id')
    op.alter_column('users', 'email',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('users', 'phone',
               existing_type=mysql.VARCHAR(length=255),
               type_=sqlmodel.sql.sqltypes.AutoString(length=12),
               existing_nullable=True)
    op.alter_column('users', 'address',
               existing_type=mysql.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(length=255),
               existing_nullable=True)
    op.alter_column('users', 'terms_and_condition',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('users', 'is_active',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('users', 'client_employee_id',
               existing_type=mysql.VARCHAR(length=100),
               type_=sqlmodel.sql.sqltypes.AutoString(length=255),
               existing_nullable=True)
    op.alter_column('users', 'pincode',
               existing_type=mysql.VARCHAR(length=100),
               type_=sqlmodel.sql.sqltypes.AutoString(length=10),
               existing_nullable=True)
    op.alter_column('users', 'district',
               existing_type=mysql.VARCHAR(length=100),
               type_=sqlmodel.sql.sqltypes.AutoString(length=255),
               existing_nullable=True)
    op.alter_column('users', 'state',
               existing_type=mysql.VARCHAR(length=100),
               type_=sqlmodel.sql.sqltypes.AutoString(length=255),
               existing_nullable=True)
    op.alter_column('users', 'password',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.alter_column('users', 'password',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('users', 'state',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=255),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('users', 'district',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=255),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('users', 'pincode',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=10),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('users', 'client_employee_id',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=255),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('users', 'is_active',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text('1'))
    op.alter_column('users', 'terms_and_condition',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('users', 'address',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=255),
               type_=mysql.TEXT(),
               existing_nullable=True)
    op.alter_column('users', 'phone',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=12),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('users', 'email',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.add_column('quotations', sa.Column('customer_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('quotations', sa.Column('total_amount', mysql.DECIMAL(precision=12, scale=2), nullable=True))
    op.add_column('quotations', sa.Column('valid_until', mysql.DATETIME(), nullable=True))
    op.add_column('quotations', sa.Column('created_by', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('quotations', sa.Column('status', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('quotations', sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('current_timestamp()'), nullable=True))
    op.create_foreign_key(op.f('fk_quotations_creator'), 'quotations', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_quotations_customer'), 'quotations', 'users', ['customer_id'], ['id'], ondelete='SET NULL')
    op.drop_column('quotations', 'price')
    op.drop_column('quotations', 'name')
    op.drop_column('quotations', 'total_price')
    op.drop_column('quotations', 'quantity')
    op.drop_column('quotations', 'product_id')
    op.add_column('products', sa.Column('category', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('products', sa.Column('description', mysql.TEXT(), nullable=True))
    op.add_column('products', sa.Column('stock_quantity', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.alter_column('products', 'price',
               existing_type=sa.Float(),
               type_=mysql.DECIMAL(precision=12, scale=2),
               nullable=True)
    op.alter_column('products', 'name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.create_table('bills',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('quotation_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('customer_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('total_amount', mysql.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('status', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('current_timestamp()'), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['users.id'], name=op.f('fk_bills_customer'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['quotation_id'], ['quotations.id'], name=op.f('fk_bills_quotation'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('quotation_items',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('quotation_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('product_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('quantity', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('unit_price', mysql.DECIMAL(precision=12, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_qi_product'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['quotation_id'], ['quotations.id'], name=op.f('fk_qi_quotation'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('projects',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('quotation_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('customer_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('employee_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('title', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('description', mysql.TEXT(), nullable=True),
    sa.Column('status', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('assigned_at', mysql.DATETIME(), nullable=True),
    sa.Column('completed_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['users.id'], name=op.f('fk_projects_customer'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['employee_id'], ['users.id'], name=op.f('fk_projects_employee'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['quotation_id'], ['quotations.id'], name=op.f('fk_projects_quotation'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('quotation_requests',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('customer_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('full_name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('email', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('phone', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('service_type', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('installation_address', mysql.TEXT(), nullable=True),
    sa.Column('description', mysql.TEXT(), nullable=True),
    sa.Column('status', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('assigned_admin_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('current_timestamp()'), nullable=True),
    sa.ForeignKeyConstraint(['assigned_admin_id'], ['users.id'], name=op.f('fk_qr_admin'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['customer_id'], ['users.id'], name=op.f('fk_qr_customer'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
